import type { Portfolio, AssetClass, MandateLimit, Policy, AssetClassThresholdConfig } from '../types.ts';

export const initialPolicies: Policy[] = [
  {
    id: 'IPS-AW-001',
    code: 'IPS-AW-001',
    name: 'Mandato Bilateral Carteira Miguel (IPS Registrado)',
    type: 'MANDATO_CLIENTE',
    version: 'v2.4',
    effectiveDate: '01/01/2026',
    description: 'Declaração formal de política de investimentos (IPS) acordada bilateralmente com o titular e arquivada para fins de auditoria.',
    status: 'ACTIVE',
    rules: [
      {
        id: 'rul-aw-01',
        policyId: 'IPS-AW-001',
        assetClass: 'Renda Variável',
        profile: 'Moderado',
        minPercent: 10,
        targetPercent: 25,
        maxPercent: 35,
        tolerancePP: 5.0,
        source: 'MANDATO_CLIENTE',
        strictness: 'HARD_STOP',
        effectiveDate: '01/01/2026',
        description: 'Teto máximo de ações locais estipulado no mandato do cliente Miguel.',
      },
      {
        id: 'rul-aw-02',
        policyId: 'IPS-AW-001',
        assetClass: 'Renda Fixa',
        profile: 'Moderado',
        minPercent: 40,
        targetPercent: 50,
        maxPercent: 65,
        tolerancePP: 5.0,
        source: 'MANDATO_CLIENTE',
        strictness: 'HARD_STOP',
        effectiveDate: '01/01/2026',
      },
      {
        id: 'rul-aw-03',
        policyId: 'IPS-AW-001',
        assetClass: 'Caixa',
        profile: 'Moderado',
        minPercent: 2,
        targetPercent: 5,
        maxPercent: 10,
        tolerancePP: 2.0,
        source: 'MANDATO_CLIENTE',
        strictness: 'WARNING_TOLERANCE',
        effectiveDate: '01/01/2026',
      },
    ],
  },
  {
    id: 'POL-PREV-001',
    code: 'POL-HORIZON-PREV',
    name: 'Diretriz Interna de Alocação e Risco Previdenciário',
    type: 'POLITICA_INTERNA',
    version: 'v3.1',
    effectiveDate: '15/12/2025',
    description: 'Manual interno de risco e alocação do comitê de investimentos para mandatos de previdência PGBL/VGBL.',
    status: 'ACTIVE',
    rules: [
      {
        id: 'rul-hz-01',
        policyId: 'POL-HORIZON-PREV',
        assetClass: 'Multimercado',
        profile: 'Conservador',
        minPercent: 0,
        targetPercent: 10,
        maxPercent: 15,
        tolerancePP: 3.0,
        source: 'POLITICA_INTERNA',
        strictness: 'WARNING_TOLERANCE',
        effectiveDate: '15/12/2025',
        description: 'Limite interno da gestora para exposição a fundos multimercados.',
      },
    ],
  },
  {
    id: 'CVM-175-ANEXO-I',
    code: 'CVM-175-ANEXO-I',
    name: 'Resolução CVM 175 - Limites de Ativos no Exterior & Liquidez',
    type: 'REGRA_REGULATORIA',
    version: 'Res. CVM 175',
    effectiveDate: '02/10/2023',
    description: 'Regulamentação geral de fundos de investimento e carteiras administradas pela CVM, Anexo Normativo I.',
    status: 'ACTIVE',
    rules: [
      {
        id: 'rul-cvm-01',
        policyId: 'CVM-175-ANEXO-I',
        assetClass: 'Internacional',
        profile: 'Arrojado',
        minPercent: 0,
        targetPercent: 20,
        maxPercent: 25,
        tolerancePP: 5.0,
        source: 'REGRA_REGULATORIA',
        strictness: 'HARD_STOP',
        effectiveDate: '02/10/2023',
        description: 'Teto de 25% para investidores qualificados sem anexo específico de exterior.',
      },
    ],
  },
  {
    id: 'RES-CMN-4963-RPPS',
    code: 'RES-CMN-4963-RPPS',
    name: 'Resolução CMN nº 4.963/2021 - Aplicações dos Regimes Próprios (RPPS)',
    type: 'REGRA_REGULATORIA',
    version: 'CMN 4.963',
    effectiveDate: '25/11/2021',
    description: 'Diretrizes do Conselho Monetário Nacional para limites de alocação de recursos previdenciários de servidores públicos.',
    status: 'ACTIVE',
    rules: [
      {
        id: 'rul-rpps-01',
        policyId: 'RES-CMN-4963-RPPS',
        assetClass: 'Renda Variável',
        profile: 'Moderado',
        minPercent: 15,
        targetPercent: 25,
        maxPercent: 35,
        tolerancePP: 3.5,
        source: 'REGRA_REGULATORIA',
        strictness: 'HARD_STOP',
        effectiveDate: '25/11/2021',
        description: 'Teto de alocação em ações e índices para RPPS no segmento de renda variável.',
      },
    ],
  },
  {
    id: 'SUIT-MODERADO-V2',
    code: 'SUIT-MODERADO-V2',
    name: 'Matriz de Adequação de Suitability CVM 30 - Moderado',
    type: 'SUITABILITY',
    version: 'v2.0',
    effectiveDate: '01/06/2024',
    description: 'Limites de risco para perfil de investidor Moderado conforme regras de suitability da CVM e ANBIMA.',
    status: 'ACTIVE',
    rules: [
      {
        id: 'rul-suit-01',
        policyId: 'SUIT-MODERADO-V2',
        assetClass: 'Renda Variável',
        profile: 'Moderado',
        minPercent: 0,
        targetPercent: 20,
        maxPercent: 35,
        tolerancePP: 5.0,
        source: 'SUITABILITY',
        strictness: 'HARD_STOP',
        effectiveDate: '01/06/2024',
      },
    ],
  },
];

export const initialPortfolios: Portfolio[] = [
  {
    id: 'port-miguel-001',
    name: 'Carteira Miguel',
    clientName: 'Miguel',
    code: 'MIGUEL-001',
    manager: 'MPX Wealth Management',
    profile: 'Arrojado',
    benchmark: 'CDI',
    totalAum: 3999016.90,
    cashBalance: 0,
    lastRebalanced: '20/01/2026',
    status: 'NORMAL',
    assignedPolicyId: 'IPS-AW-001',
    mandateLimits: [
      { assetClass: 'Renda Fixa', targetPercent: 50, minPercent: 40, maxPercent: 65 },
      { assetClass: 'Renda Variável', targetPercent: 25, minPercent: 10, maxPercent: 35 },
      { assetClass: 'Internacional', targetPercent: 15, minPercent: 5, maxPercent: 25 },
      { assetClass: 'Multimercado', targetPercent: 5, minPercent: 0, maxPercent: 15 },
      { assetClass: 'Caixa', targetPercent: 5, minPercent: 2, maxPercent: 10 },
    ],
    assets: [
      {
        id: 'ast-miguel-cdb-001',
        ticker: 'CDB-BBA-001',
        name: 'CDB ITAU BBA POS',
        assetClass: 'Renda Fixa',
        sector: 'Pós-fixado',
        quantity: 100,
        currentPrice: 1000,
        totalValue: 100000.00,
        allocationPercent: 2.5,
        productType: 'tesouraria_banco',
        isTaxExempt: false,
      },
      // ── Pós-fixado — 9 produtos, R$ 3.028.755,91 (Itaú) ──
      {
        id: 'ast-miguel-52678',
        ticker: '52678',
        name: 'DIF CP FICFI',
        assetClass: 'Renda Fixa',
        sector: 'Pós-fixado',
        quantity: 25362.95,
        currentPrice: 30.88711,
        totalValue: 783388.21,
        allocationPercent: 19.59,
        targetPercent: 15.00,
        driftTolerancePP: 2.5,
        cnpj: '20.335.522/0001-51',
        productType: 'asset_gestora',
        isTaxExempt: false,
        historicalPerformance: { twelveMonths: 14.08, twentyFourMonths: 29.10 },
      },
      {
        id: 'ast-miguel-56732',
        ticker: '56732',
        name: 'ITAÚ CRÉD BANCÁRIO',
        assetClass: 'Renda Fixa',
        sector: 'Pós-fixado',
        quantity: 402846.98,
        currentPrice: 1.4612,
        totalValue: 588640.00,
        allocationPercent: 14.72,
        targetPercent: 12.00,
        driftTolerancePP: 2.5,
        cnpj: '51.998.694/0001-39',
        productType: 'asset_gestora',
        isTaxExempt: false,
        historicalPerformance: { twelveMonths: 14.61, twentyFourMonths: 29.61, thirtySixMonths: 45.51 },
      },
      {
        id: 'ast-miguel-56855',
        ticker: '56855',
        name: 'OCCAM LIQUIDEZ',
        assetClass: 'Renda Fixa',
        sector: 'Pós-fixado',
        quantity: 293187.23,
        currentPrice: 1.750704,
        totalValue: 513284.04,
        allocationPercent: 12.84,
        targetPercent: 13.00,
        driftTolerancePP: 2.5,
        productType: 'asset_gestora',
        isTaxExempt: false,
      },
      {
        id: 'ast-miguel-59138',
        ticker: '59138',
        name: 'SEL KINEA ATACAMA RF',
        assetClass: 'Renda Fixa',
        sector: 'Pós-fixado',
        quantity: 465508.63,
        currentPrice: 1.039109,
        totalValue: 483714.18,
        allocationPercent: 12.10,
        targetPercent: 15.00,
        driftTolerancePP: 2.5,
        cnpj: '08.604.187/0001-44',
        productType: 'asset_gestora',
        isTaxExempt: false,
      },
      {
        id: 'ast-miguel-58336',
        ticker: '58336',
        name: 'MAPFRE CONFIANZA RF',
        assetClass: 'Renda Fixa',
        sector: 'Pós-fixado',
        quantity: 204466.5,
        currentPrice: 1.505606,
        totalValue: 307845.95,
        allocationPercent: 7.70,
        targetPercent: 8.00,
        driftTolerancePP: 2.5,
        productType: 'asset_gestora',
        isTaxExempt: false,
      },
      {
        id: 'ast-miguel-57559',
        ticker: '57559',
        name: 'BTG PACTUAL CORP SEL',
        assetClass: 'Renda Fixa',
        sector: 'Pós-fixado',
        quantity: 195142.28,
        currentPrice: 1.307091,
        totalValue: 255068.71,
        allocationPercent: 6.38,
        productType: 'asset_gestora',
        isTaxExempt: false,
      },
      {
        id: 'ast-miguel-58989',
        ticker: '58989',
        name: 'ITAÚ SELEÇÃO IBIUNA',
        assetClass: 'Renda Fixa',
        sector: 'Pós-fixado',
        quantity: 86203.35,
        currentPrice: 1.063998,
        totalValue: 91720.18,
        allocationPercent: 2.29,
        productType: 'asset_gestora',
        isTaxExempt: false,
      },
      {
        id: 'ast-miguel-54170',
        ticker: '54170',
        name: 'JGP SELECT FICFI MM',
        assetClass: 'Renda Fixa',
        sector: 'Pós-fixado',
        quantity: 253.5,
        currentPrice: 20.093145,
        totalValue: 5093.56,
        allocationPercent: 0.13,
        productType: 'asset_gestora',
        isTaxExempt: false,
      },
      {
        id: 'ast-miguel-atenas',
        ticker: 'ATENAS-VGBL',
        name: 'Itau Absolute Atenas Prev Rf Cp Vgbl',
        assetClass: 'Renda Fixa',
        sector: 'Pós-fixado',
        quantity: 0.69,
        currentPrice: 1.564843,
        totalValue: 1.08,
        allocationPercent: 0.00,
        productType: 'asset_gestora',
        isTaxExempt: false,
      },

      // ── Renda Fixa Ativo — 3 produtos, R$ 462.390,45 (Itaú) ──
      {
        id: 'ast-miguel-56294',
        ticker: '56294',
        name: 'BTG PACTUAL RF SEL',
        assetClass: 'Renda Fixa',
        sector: 'Renda Fixa Ativo',
        quantity: 170721.21,
        currentPrice: 1.498636,
        totalValue: 255848.95,
        allocationPercent: 6.40,
        productType: 'asset_gestora',
        isTaxExempt: false,
      },
      {
        id: 'ast-miguel-58343',
        ticker: '58343',
        name: 'VINLAND RF ATIVO SEL',
        assetClass: 'Renda Fixa',
        sector: 'Renda Fixa Ativo',
        quantity: 137387.82,
        currentPrice: 1.119348,
        totalValue: 153784.76,
        allocationPercent: 3.85,
        productType: 'asset_gestora',
        isTaxExempt: false,
      },
      {
        id: 'ast-miguel-50246',
        ticker: '50246',
        name: 'ITAÚ BTG PACTUAL RF',
        assetClass: 'Renda Fixa',
        sector: 'Renda Fixa Ativo',
        quantity: 882.48,
        currentPrice: 59.782514,
        totalValue: 52756.74,
        allocationPercent: 1.32,
        productType: 'asset_gestora',
        isTaxExempt: false,
      },

      // ── Inflação — 1 produto, R$ 152.171,68 (Itaú) ──
      {
        id: 'ast-miguel-56081',
        ticker: '56081',
        name: 'ICATU VANGUARDA INFR',
        assetClass: 'Renda Fixa',
        sector: 'Inflação',
        quantity: 106647.95,
        currentPrice: 1.42686,
        totalValue: 152171.68,
        allocationPercent: 3.81,
        productType: 'asset_gestora',
        isTaxExempt: true,
        taxExemptionReason: 'Fundo de Debêntures Incentivadas',
      },

      // ── Multimercado — 2 produtos, R$ 105.106,46 (Itaú) ──
      {
        id: 'ast-miguel-54430',
        ticker: '54430',
        name: 'KINEA APOLO FIC MM',
        assetClass: 'Multimercado',
        sector: 'Multimercado',
        quantity: 5305.25,
        currentPrice: 18.84927,
        totalValue: 100000.00,
        allocationPercent: 2.50,
        productType: 'asset_gestora',
        isTaxExempt: false,
      },
      {
        id: 'ast-miguel-54169',
        ticker: '54169',
        name: 'JGP CORPORATE PLUS',
        assetClass: 'Multimercado',
        sector: 'Multimercado',
        quantity: 251.27,
        currentPrice: 20.322752,
        totalValue: 5106.46,
        allocationPercent: 0.13,
        productType: 'asset_gestora',
        isTaxExempt: false,
      },

      // ── Avenue (offshore, USD convertido a 5,27) — 2 produtos ──
      {
        id: 'ast-miguel-sgov',
        ticker: 'SGOV',
        name: 'iShares 0-3 Month Treasury Bond ETF',
        assetClass: 'Internacional',
        sector: 'Avenue — orig. US$ 24.965,80 @ 5,27',
        quantity: 248,
        currentPrice: 529.8458,
        averagePrice: 530.5836,
        totalValue: 131569.77,
        unrealizedGainBRL: -183.19,
        unrealizedGainPercent: -0.13,
        allocationPercent: 3.29,
        productType: 'corretora',
        isTaxExempt: false,
      },
      {
        id: 'ast-miguel-tflo',
        ticker: 'TFLO',
        name: 'iShares Treasury Floating Rate Bond ETF',
        assetClass: 'Internacional',
        sector: 'Avenue — orig. US$ 22.584,94 @ 5,27',
        quantity: 447,
        currentPrice: 266.5566,
        averagePrice: 266.9255,
        totalValue: 119022.63,
        unrealizedGainBRL: -164.69,
        unrealizedGainPercent: -0.13,
        allocationPercent: 2.98,
        productType: 'corretora',
        isTaxExempt: false,
      },
    ],
  },
{
  id: 'port-wilson-001',
  name: 'Carteira Wilson',
  clientName: 'Wilson',
  code: 'WILSON-001',
  manager: 'MPX Wealth Management',
  profile: 'Arrojado',
  benchmark: 'CDI',
  totalAum: 2078568.86,
  cashBalance: 0,
  lastRebalanced: '10/01/2026',
  status: 'NORMAL',
  assignedPolicyId: 'IPS-WILSON-001',
  mandateLimits: [
    { assetClass: 'Renda Fixa', targetPercent: 60, minPercent: 45, maxPercent: 75 },
    { assetClass: 'Multimercado', targetPercent: 15, minPercent: 5, maxPercent: 25 },
    { assetClass: 'Renda Variável', targetPercent: 15, minPercent: 5, maxPercent: 25 },
    { assetClass: 'Internacional', targetPercent: 5, minPercent: 0, maxPercent: 15 },
    { assetClass: 'Caixa', targetPercent: 5, minPercent: 1, maxPercent: 10 },
  ],
  assets: [
    {
      id: 'ast-wilson-itau-deb-incent-posfix',
      ticker: 'ITAU-DEB-INCENT-POSFIX',
      name: "Itaú Debêntures Incentivadas Pós-Fixado Renda Fixa",
      assetClass: 'Renda Fixa',
      sector: 'Fundo — Pós-fixado (CDI)',
      totalValue: 186141.70,
      allocationPercent: 8.96,
      targetPercent: 6.00,
      driftTolerancePP: 2.5,
    },
    {
      id: 'ast-wilson-itau-index-us-tech-acoes',
      ticker: 'ITAU-INDEX-US-TECH-ACOES',
      name: "Itaú Index US Tech Ações",
      assetClass: 'Internacional',
      sector: 'Fundo — Índice EUA (Tech)',
      totalValue: 95850.90,
      allocationPercent: 4.61,
      targetPercent: 5.00,
      driftTolerancePP: 2.5,
    },
    {
      id: 'ast-wilson-itau-janeiro-multimercado',
      ticker: 'ITAU-JANEIRO-MULTIMERCADO',
      name: "Itaú Janeiro Multimercado",
      assetClass: 'Multimercado',
      sector: 'Fundo — Multimercado',
      totalValue: 75635.44,
      allocationPercent: 3.64,
      targetPercent: 4.00,
      driftTolerancePP: 2.5,
    },
    {
      id: 'ast-wilson-absolute-hidra-cdi',
      ticker: 'ABSOLUTE-HIDRA-CDI-INFRA-RF-CP',
      name: "Absolute Hidra CDI Seleção Infra Renda Fixa CP",
      assetClass: 'Renda Fixa',
      sector: 'Fundo — Crédito Privado',
      totalValue: 65715.25,
      allocationPercent: 3.16,
      targetPercent: 3.00,
      driftTolerancePP: 2.5,
    },
    {
      id: 'ast-wilson-itau-sinfonia-mm-cp',
      ticker: 'ITAU-SINFONIA-MM-CREDITO-PRIVADO',
      name: "Itaú Sinfonia Multimercado Crédito Privado",
      assetClass: 'Multimercado',
      sector: 'Fundo — Crédito Privado',
      totalValue: 25410.96,
      allocationPercent: 1.22,
      targetPercent: 2.00,
      driftTolerancePP: 2.5,
    },
    {
      id: 'ast-wilson-diferenciado-cp-rf',
      ticker: 'DIFERENCIADO-CREDITO-PRIVADO-RF',
      name: "Diferenciado Crédito Privado Renda Fixa",
      assetClass: 'Renda Fixa',
      sector: 'Fundo — Crédito Privado',
      totalValue: 70.62,
      allocationPercent: 0.00,
      targetPercent: 0.00,
      driftTolerancePP: 2.5,
    },
    {
      id: 'ast-wilson-flexprev-sinfonia-vgbl',
      ticker: 'FLEXPREV-SINFONIA-MMCP-VGBL',
      name: "Flexprev Sinfonia Mm Cp Vgbl",
      assetClass: 'Multimercado',
      sector: 'Previdência — Multimercado Crédito Privado',
      totalValue: 173301.93,
      allocationPercent: 8.34,
      targetPercent: 5.00,
      driftTolerancePP: 2.5,
    },
    {
      id: 'ast-wilson-itau-advanced-pvt-prev',
      ticker: 'ITAU-ADVANCED-PVT-MARKETS-PREV-VGBL',
      name: "Itau Advanced Pvt Markets Prev Mmcp Vgbl",
      assetClass: 'Multimercado',
      sector: 'Previdência — Multimercado Crédito Privado',
      totalValue: 164635.11,
      allocationPercent: 7.92,
      targetPercent: 5.00,
      driftTolerancePP: 2.5,
    },
    {
      id: 'ast-wilson-deb-origemenergia-pre',
      ticker: 'DEB-ORIGEM-ENERGIA-PRE-1235',
      name: "DEB Origem Energia PRE 14,7% 15/12/2035",
      assetClass: 'Renda Fixa',
      sector: 'Prefixado',
      totalValue: 93924.00,
      allocationPercent: 4.52,
    },
    {
      id: 'ast-wilson-cpr-klabin',
      ticker: 'CPR-KLABIN-IPCA-656-0835',
      name: "CPR Klabin S.A. IPCA 6,56% 15/08/2035",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 77680.18,
      allocationPercent: 3.74,
    },
    {
      id: 'ast-wilson-deb-ecorodovias',
      ticker: 'DEB-ECORODOVIAS-IPCA-702-0639',
      name: "DEB Ecorodovias IPCA 7,02% 15/06/2039",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 64687.30,
      allocationPercent: 3.11,
    },
    {
      id: 'ast-wilson-cri-jhsf',
      ticker: 'CRI-JHSF-IPCA-755-1034',
      name: "CRI JHSF IPCA 7,55% 16/10/2034",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 64476.17,
      allocationPercent: 3.10,
    },
    {
      id: 'ast-wilson-deb-vale-619',
      ticker: 'DEB-VALE-IPCA-619-0535',
      name: "DEB Vale IPCA 6,19% 15/05/2035",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 58311.17,
      allocationPercent: 2.81,
    },
    {
      id: 'ast-wilson-deb-petrobras',
      ticker: 'DEB-PETROBRAS-IPCA-59-0640',
      name: "DEB Petrobras IPCA 5,9% 15/06/2040",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 57561.27,
      allocationPercent: 2.77,
    },
    {
      id: 'ast-wilson-deb-enauta',
      ticker: 'DEB-ENAUTA-IPCA-719-0630',
      name: "DEB Enauta IPCA 7,19% 15/06/2030",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 50792.71,
      allocationPercent: 2.44,
    },
    {
      id: 'ast-wilson-deb-brava',
      ticker: 'DEB-BRAVA-ENERGIA-IPCA-693-1033',
      name: "DEB Brava Energia IPCA 6,93% 15/10/2033",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 50138.34,
      allocationPercent: 2.41,
    },
    {
      id: 'ast-wilson-deb-isacteep',
      ticker: 'DEB-ISACTEEP-IPCA-631-0635',
      name: "DEB ISA CTEEP IPCA 6,31% 15/06/2035",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 49377.26,
      allocationPercent: 2.38,
    },
    {
      id: 'ast-wilson-cri-bild',
      ticker: 'CRI-BILD-PRE-1472-1130',
      name: "CRI Bild PRE 14,72% 18/11/2030",
      assetClass: 'Renda Fixa',
      sector: 'Prefixado',
      totalValue: 48565.77,
      allocationPercent: 2.34,
    },
    {
      id: 'ast-wilson-cra-zilor-1423',
      ticker: 'CRA-ZILOR-PRE-1423-1132',
      name: "CRA Zilor PRE 14,23% 15/11/2032",
      assetClass: 'Renda Fixa',
      sector: 'Prefixado',
      totalValue: 48046.11,
      allocationPercent: 2.31,
    },
    {
      id: 'ast-wilson-deb-celpe',
      ticker: 'DEB-CELPE-IPCA-631-0835',
      name: "DEB Celpe IPCA 6,31% 15/08/2035",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 47271.82,
      allocationPercent: 2.27,
    },
    {
      id: 'ast-wilson-deb-igua',
      ticker: 'DEB-IGUA-RJ-IPCA-833-0734',
      name: "DEB Igua RJ IPCA 8,33% 15/07/2034",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 44829.44,
      allocationPercent: 2.16,
    },
    {
      id: 'ast-wilson-deb-equatorial',
      ticker: 'DEB-EQUATORIAL-MARANHAO-IPCA-613-1231',
      name: "DEB Equatorial Maranhão IPCA 6,13% 15/12/2031",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 38276.20,
      allocationPercent: 1.84,
    },
    {
      id: 'ast-wilson-deb-taesa',
      ticker: 'DEB-TAESA-IPCA-616-1240',
      name: "DEB Taesa IPCA 6,16% 15/12/2040",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 37505.29,
      allocationPercent: 1.80,
    },
    {
      id: 'ast-wilson-deb-energisa',
      ticker: 'DEB-ENERGISA-MG-IPCA-624-1035',
      name: "DEB Energisa MG IPCA 6,24% 15/10/2035",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 32668.97,
      allocationPercent: 1.57,
    },
    {
      id: 'ast-wilson-cri-salta',
      ticker: 'CRI-SALTA-IPCA-77-0331',
      name: "CRI Salta IPCA 7,7% 17/03/2031",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 30509.47,
      allocationPercent: 1.47,
    },
    {
      id: 'ast-wilson-cra-zilor-1441',
      ticker: 'CRA-ZILOR-PRE-1441-1132',
      name: "CRA Zilor PRE 14,41% 15/11/2032",
      assetClass: 'Renda Fixa',
      sector: 'Prefixado',
      totalValue: 28435.45,
      allocationPercent: 1.37,
    },
    {
      id: 'ast-wilson-cri-solfacil',
      ticker: 'CRI-SOLFACIL-PRE-124-0131',
      name: "CRI Sólfácil PRE 12,4% 15/01/2031",
      assetClass: 'Renda Fixa',
      sector: 'Prefixado',
      totalValue: 25836.38,
      allocationPercent: 1.24,
    },
    {
      id: 'ast-wilson-deb-vale-62',
      ticker: 'DEB-VALE-IPCA-62-0535',
      name: "DEB Vale IPCA 6,2% 15/05/2035",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 13782.64,
      allocationPercent: 0.66,
    },
    {
      id: 'ast-wilson-sp500-ganho-garantido',
      ticker: 'SP500-GANHO-GARANTIDO',
      name: "SP 500 Ganho Garantido",
      assetClass: 'Internacional',
      sector: 'Estruturado (COE)',
      totalValue: 129934.74,
      allocationPercent: 6.25,
    },
    {
      id: 'ast-wilson-cdb-di-unico',
      ticker: 'CDB-DI-UNICO',
      name: "CDB-DI",
      assetClass: 'Renda Fixa',
      sector: 'Pós-fixado (CDI)',
      totalValue: 23382.62,
      allocationPercent: 1.12,
    },
    {
      id: 'ast-wilson-avenue-sgov',
      ticker: 'SGOV',
      name: "iShares 0-3 Month Treasury Bond ETF",
      assetClass: 'Renda Fixa',
      sector: 'Avenue — offshore',
      quantity: 129,
      currentPrice: 530.90,
      averagePrice: 530.53,
      totalValue: 68691.22,
      allocationPercent: 3.30,
    },
    {
      id: 'ast-wilson-avenue-shv',
      ticker: 'SHV',
      name: "iShares Short Treasury Bond ETF",
      assetClass: 'Renda Fixa',
      sector: 'Avenue — offshore',
      quantity: 93,
      currentPrice: 581.64,
      averagePrice: 581.54,
      totalValue: 54262.61,
      allocationPercent: 2.61,
    },
    {
      id: 'ast-wilson-avenue-tflo',
      ticker: 'TFLO',
      name: "iShares Treasury Floating Rate Bond ETF",
      assetClass: 'Renda Fixa',
      sector: 'Avenue — offshore',
      quantity: 198,
      currentPrice: 267.12,
      averagePrice: 266.85,
      totalValue: 52859.82,
      allocationPercent: 2.54,
    },
  ],
},
  {
  id: 'port-dario-001',
  name: 'Carteira Dário',
  clientName: 'Dário Marques Neto',
  code: 'DARIO-001',
  manager: 'MPX Wealth Management',
  profile: 'Arrojado',
  benchmark: 'CDI',
  totalAum: 728022.72,
  cashBalance: 0,
  lastRebalanced: '15/01/2026',
  status: 'NORMAL',
  assignedPolicyId: 'IPS-DARIO-001',
  mandateLimits: [
    { assetClass: 'Renda Fixa', targetPercent: 40, minPercent: 25, maxPercent: 55 },
    { assetClass: 'Internacional', targetPercent: 30, minPercent: 15, maxPercent: 45 },
    { assetClass: 'Multimercado', targetPercent: 15, minPercent: 5, maxPercent: 25 },
    { assetClass: 'Renda Variável', targetPercent: 10, minPercent: 0, maxPercent: 20 },
    { assetClass: 'Caixa', targetPercent: 5, minPercent: 1, maxPercent: 10 },
  ],
  assets: [
    // ══════════════ ITAÚ — R$ 450.740,14 ══════════════
    // ── Fundos de Investimento — 15 fundos, R$ 235.994,68 ──
    {
      id: 'ast-dario-itubers-deb-cdi',
      ticker: 'ITUBERS-DEB-CDI',
      name: 'Itubers Debêntures Incentivadas CDI RF',
      assetClass: 'Renda Fixa',
      totalValue: 37173.23,
      allocationPercent: 5.11,
    },
    {
      id: 'ast-dario-itau-deb-posf',
      ticker: 'ITAU-DEB-POSF',
      name: 'Itaú Debêntures Incentivadas Pós-Fixado Renda Fixa',
      assetClass: 'Renda Fixa',
      totalValue: 30685.28,
      allocationPercent: 4.21,
    },
    {
      id: 'ast-dario-itau-itubers-di',
      ticker: 'ITAU-ITUBERS-DI',
      name: 'Itaú Itubers RF Referenciado DI',
      assetClass: 'Renda Fixa',
      totalValue: 27644.60,
      allocationPercent: 3.80,
    },
    {
      id: 'ast-dario-itau-deb-cdi-cp',
      ticker: 'ITAU-DEB-CDI-CP',
      name: 'Itaú Debêntures Incentivadas CDI RF CP',
      assetClass: 'Renda Fixa',
      totalValue: 27290.35,
      allocationPercent: 3.75,
    },
    {
      id: 'ast-dario-itau-legend-infra',
      ticker: 'ITAU-LEGEND-INFRA',
      name: 'Itaú Legend Infra Renda Fixa Crédito Privado',
      assetClass: 'Renda Fixa',
      totalValue: 22570.16,
      allocationPercent: 3.10,
    },
    {
      id: 'ast-dario-itau-artax-infra',
      ticker: 'ITAU-ARTAX-INFRA',
      name: 'Itaú Artax Infra Incentivado RF LP - RL',
      assetClass: 'Renda Fixa',
      totalValue: 21584.97,
      allocationPercent: 2.96,
    },
    {
      id: 'ast-dario-absolute-hidra',
      ticker: 'ABSOLUTE-HIDRA-CDI',
      name: 'Absolute Hidra CDI Seleção Infra Renda Fixa CP',
      assetClass: 'Renda Fixa',
      totalValue: 21522.76,
      allocationPercent: 2.96,
    },
    {
      id: 'ast-dario-itau-janeiro-infra',
      ticker: 'ITAU-JANEIRO-INFRA',
      name: 'Itaú Janeiro Infra Incentivado Renda Fixa',
      assetClass: 'Renda Fixa',
      totalValue: 12827.68,
      allocationPercent: 1.76,
    },
    {
      id: 'ast-dario-itau-janeiro-lp',
      ticker: 'ITAU-JANEIRO-LP',
      name: 'Itaú Janeiro Renda Fixa Longo Prazo',
      assetClass: 'Renda Fixa',
      totalValue: 11552.68,
      allocationPercent: 1.59,
    },
    {
      id: 'ast-dario-itau-global-dinamico-infra',
      ticker: 'ITAU-GLOBAL-DINAMICO-INFRA',
      name: 'Itaú Global Dinâmico Infra Renda Fixa Longo Prazo',
      assetClass: 'Renda Fixa',
      totalValue: 10779.25,
      allocationPercent: 1.48,
    },
    {
      id: 'ast-dario-itau-index-sp500',
      ticker: 'ITAU-INDEX-SP500',
      name: 'Itaú Index Ações Estratégia S&P 500',
      assetClass: 'Internacional',
      totalValue: 8134.64,
      allocationPercent: 1.12,
    },
    {
      id: 'ast-dario-itau-credito-bancario',
      ticker: 'ITAU-CREDITO-BANCARIO',
      name: 'Itaú Crédito Bancário Renda Fixa Crédito Privado',
      assetClass: 'Renda Fixa',
      totalValue: 2471.88,
      allocationPercent: 0.34,
    },
    {
      id: 'ast-dario-porto-paineira',
      ticker: 'PORTO-PAINEIRA-CDI',
      name: 'Porto Paineira CDI Seleção Infra Renda Fixa',
      assetClass: 'Renda Fixa',
      totalValue: 1116.06,
      allocationPercent: 0.15,
    },
    {
      id: 'ast-dario-itau-global-dinamico-lp',
      ticker: 'ITAU-GLOBAL-DINAMICO-LP',
      name: 'Itaú Global Dinâmico Renda Fixa Longo Prazo',
      assetClass: 'Renda Fixa',
      totalValue: 629.59,
      allocationPercent: 0.09,
    },
    {
      id: 'ast-dario-privilege-di',
      ticker: 'PRIVILEGE-DI',
      name: 'Privilege DI',
      assetClass: 'Renda Fixa',
      totalValue: 11.55,
      allocationPercent: 0.00,
    },

    // ── CDB, Renda Fixa e Estruturados — 1 posição, R$ 106.544,41 ──
    {
      id: 'ast-dario-cdb-di',
      ticker: 'CDB-DI',
      name: 'CDB-DI',
      assetClass: 'Renda Fixa',
      totalValue: 106544.41,
      allocationPercent: 14.63,
    },

    // ── Previdência — 3 posições, R$ 96.664,14 ──
    {
      id: 'ast-dario-pgbl-itubers-rf',
      ticker: 'PGBL-ITUBERS-RF',
      name: 'Pgbl Itubers Rf',
      assetClass: 'Renda Fixa',
      totalValue: 64574.65,
      allocationPercent: 8.87,
    },
    {
      id: 'ast-dario-absolute-delfos-prev',
      ticker: 'ABSOLUTE-DELFOS-PREV',
      name: 'Itau Absolute Delfos Prev Rf Cp Vgbl',
      assetClass: 'Renda Fixa',
      totalValue: 23887.81,
      allocationPercent: 3.28,
    },
    {
      id: 'ast-dario-pgbl-itubers-kinea',
      ticker: 'PGBL-ITUBERS-KINEA',
      name: 'Pgbl Itubers Kinea Prev Cp Rf',
      assetClass: 'Renda Fixa',
      totalValue: 8201.68,
      allocationPercent: 1.13,
    },

    // ── Ações (corretora) — 5 posições, R$ 11.536,91 ──
    {
      id: 'ast-dario-lfts11',
      ticker: 'LFTS11',
      name: 'INVESTO LFTS F11',
      assetClass: 'Renda Fixa',
      totalValue: 9109.17,
      allocationPercent: 1.25,
    },
    {
      id: 'ast-dario-nucl11',
      ticker: 'NUCL11',
      name: 'INVESTO NUCL CI',
      assetClass: 'Internacional',
      totalValue: 822.36,
      allocationPercent: 0.11,
    },
    {
      id: 'ast-dario-spcx34',
      ticker: 'SPCX34',
      name: 'SPACE X DRN',
      assetClass: 'Internacional',
      totalValue: 699.16,
      allocationPercent: 0.10,
    },
    {
      id: 'ast-dario-aapl34',
      ticker: 'AAPL34',
      name: 'APPLE DRN',
      assetClass: 'Internacional',
      totalValue: 677.92,
      allocationPercent: 0.09,
    },
    {
      id: 'ast-dario-nvdc34',
      ticker: 'NVDC34',
      name: 'NVIDIA CORP DRN ED',
      assetClass: 'Internacional',
      totalValue: 228.30,
      allocationPercent: 0.03,
    },

    // ══════════════ AVENUE — US$ 52.615,29 (R$ 277.282,58 @ 5,27) ══════════════

    // ── Renda fixa Avenue — total US$ 4.807,65 (R$ 25.336,31), 3 ativos ──
    {
      id: 'ast-dario-avenue-brazil-bond',
      ticker: 'BRAZIL-6.25-2036',
      name: 'Federative Republic of Brazil 6.25 22/05/36',
      assetClass: 'Internacional',
      sector: 'Avenue Tesouro — orig. US$ 1.935,05',
      totalValue: 10197.71,
      unrealizedGainBRL: -427.08,
      unrealizedGainPercent: -4.02,
      allocationPercent: 1.40,
    },
    {
      id: 'ast-dario-avenue-rededor-bond',
      ticker: 'RDEDOR-6.45-2035',
      name: "Rede D'Or Sao Luiz SA 6.45 09/09/35",
      assetClass: 'Internacional',
      sector: 'Avenue Bonds — orig. US$ 1.921,45',
      totalValue: 10126.04,
      unrealizedGainBRL: -631.50,
      unrealizedGainPercent: -5.87,
      allocationPercent: 1.39,
    },
    {
      id: 'ast-dario-avenue-suzano-bond',
      ticker: 'SUZANO-5.5-2036',
      name: 'Suzano SA 5.5 15/01/36',
      assetClass: 'Internacional',
      sector: 'Avenue Bonds — orig. US$ 951,15',
      totalValue: 5012.56,
      unrealizedGainBRL: -180.92,
      unrealizedGainPercent: -3.48,
      allocationPercent: 0.69,
    },

    // ── Fundos Avenue — 1 ativo, US$ 1.985,43 ──
    {
      id: 'ast-dario-avenue-pimco',
      ticker: 'PIMCO-GIS-EM-ST',
      name: 'PIMCO GIS EM S/T Lcl Ccy E USD Acc',
      assetClass: 'Internacional',
      sector: 'Avenue Fundos — orig. US$ 1.985,43',
      totalValue: 10463.22,
      unrealizedGainBRL: -76.78,
      unrealizedGainPercent: -0.73,
      allocationPercent: 1.44,
    },

    // ── ETFs Avenue — 24 ativos, US$ 45.822,21, 100% detalhados individualmente ──
    {
      id: 'ast-dario-avenue-vt',
      ticker: 'VT',
      name: 'Vanguard Total World Stock ETF',
      assetClass: 'Internacional',
      quantity: 45.72409,
      currentPrice: 831.6587,
      averagePrice: 842.4622,
      totalValue: 38028.06,
      unrealizedGainBRL: -492.80,
      unrealizedGainPercent: -1.28,
      allocationPercent: 5.22,
    },
    {
      id: 'ast-dario-avenue-tflo',
      ticker: 'TFLO',
      name: 'iShares Treasury Floating Rate Bond ETF',
      assetClass: 'Renda Fixa',
      quantity: 102.62911,
      currentPrice: 266.5566,
      averagePrice: 266.3985,
      totalValue: 27353.78,
      unrealizedGainBRL: 13.54,
      unrealizedGainPercent: 0.05,
      allocationPercent: 3.76,
    },
    {
      id: 'ast-dario-avenue-vti',
      ticker: 'VTI',
      name: 'Vanguard Total Stock Market ETF',
      assetClass: 'Internacional',
      quantity: 8.53218,
      currentPrice: 1963.3912,
      averagePrice: 1986.79,
      totalValue: 16751.80,
      unrealizedGainBRL: -199.89,
      unrealizedGainPercent: -1.18,
      allocationPercent: 2.30,
    },
    {
      id: 'ast-dario-avenue-shy',
      ticker: 'SHY',
      name: 'iShares 1-3 Year Treasury Bond ETF',
      assetClass: 'Renda Fixa',
      quantity: 37.42389,
      currentPrice: 428.6618,
      averagePrice: 431.613,
      totalValue: 16043.20,
      unrealizedGainBRL: -109.46,
      unrealizedGainPercent: -0.68,
      allocationPercent: 2.20,
    },
    {
      id: 'ast-dario-avenue-sgov',
      ticker: 'SGOV',
      name: 'iShares 0-3 Month Treasury Bond ETF',
      assetClass: 'Renda Fixa',
      quantity: 29.79420,
      currentPrice: 529.7931,
      averagePrice: 529.5296,
      totalValue: 15784.91,
      unrealizedGainBRL: 8.01,
      unrealizedGainPercent: 0.05,
      allocationPercent: 2.17,
    },
    {
      id: 'ast-dario-avenue-smh',
      ticker: 'SMH',
      name: 'VanEck Semiconductor ETF',
      assetClass: 'Internacional',
      quantity: 4.73197,
      currentPrice: 2850.8592,
      averagePrice: 2900.9242,
      totalValue: 13490.20,
      unrealizedGainBRL: -236.89,
      unrealizedGainPercent: -1.73,
      allocationPercent: 1.85,
    },
    {
      id: 'ast-dario-avenue-qual',
      ticker: 'QUAL',
      name: 'iShares MSCI USA Quality Factor ETF',
      assetClass: 'Internacional',
      quantity: 11.30096,
      currentPrice: 1150.8626,
      averagePrice: 1165.8294,
      totalValue: 13005.83,
      unrealizedGainBRL: -169.11,
      unrealizedGainPercent: -1.28,
      allocationPercent: 1.79,
    },
    {
      id: 'ast-dario-avenue-xle',
      ticker: 'XLE',
      name: 'The Energy Select Sector SPDR Fund',
      assetClass: 'Internacional',
      quantity: 35.47028,
      currentPrice: 346.4498,
      averagePrice: 341.7068,
      totalValue: 12288.69,
      unrealizedGainBRL: 168.22,
      unrealizedGainPercent: 1.39,
      allocationPercent: 1.69,
    },
    {
      id: 'ast-dario-avenue-aor',
      ticker: 'AOR',
      name: 'iShares Core Growth Allocation ETF',
      assetClass: 'Multimercado',
      quantity: 29.56509,
      currentPrice: 362.1544,
      averagePrice: 369.0054,
      totalValue: 10707.90,
      unrealizedGainBRL: -201.79,
      unrealizedGainPercent: -1.85,
      allocationPercent: 1.47,
    },
    {
      id: 'ast-dario-avenue-soxx',
      ticker: 'SOXX',
      name: 'iShares Semiconductor ETF',
      assetClass: 'Internacional',
      quantity: 3.99402,
      currentPrice: 2619.8751,
      averagePrice: 2692.2322,
      totalValue: 10463.85,
      unrealizedGainBRL: -289.01,
      unrealizedGainPercent: -2.69,
      allocationPercent: 1.44,
    },
    {
      id: 'ast-dario-avenue-iau',
      ticker: 'IAU',
      name: 'iShares Gold Trust',
      assetClass: 'Multimercado',
      quantity: 24.48049,
      currentPrice: 425.0255,
      averagePrice: 430.559,
      totalValue: 10404.82,
      unrealizedGainBRL: -135.44,
      unrealizedGainPercent: -1.29,
      allocationPercent: 1.43,
    },
    {
      id: 'ast-dario-avenue-vxus',
      ticker: 'VXUS',
      name: 'Vanguard Total International Stock ETF',
      assetClass: 'Internacional',
      quantity: 17.17076,
      currentPrice: 450.585,
      averagePrice: 460.3872,
      totalValue: 7736.41,
      unrealizedGainBRL: -168.75,
      unrealizedGainPercent: -2.13,
      allocationPercent: 1.06,
    },
    {
      id: 'ast-dario-avenue-qqq',
      ticker: 'QQQ',
      name: 'Invesco QQQ Trust Series 1',
      assetClass: 'Internacional',
      quantity: 1.56533,
      currentPrice: 3712.7677,
      averagePrice: 3387.7141,
      totalValue: 5811.70,
      unrealizedGainBRL: 508.82,
      unrealizedGainPercent: 9.60,
      allocationPercent: 0.80,
    },
    {
      id: 'ast-dario-avenue-vgt',
      ticker: 'VGT',
      name: 'Vanguard Information Technology ETF',
      assetClass: 'Internacional',
      quantity: 8.19890,
      currentPrice: 626.1287,
      averagePrice: 642.7819,
      totalValue: 5133.35,
      unrealizedGainBRL: -136.76,
      unrealizedGainPercent: -2.59,
      allocationPercent: 0.71,
    },
    {
      id: 'ast-dario-avenue-xlu',
      ticker: 'XLU',
      name: 'Utilities Select Sector SPDR ETF',
      assetClass: 'Internacional',
      quantity: 23.11727,
      currentPrice: 218.178,
      averagePrice: 227.9802,
      totalValue: 5043.07,
      unrealizedGainBRL: -227.19,
      unrealizedGainPercent: -4.31,
      allocationPercent: 0.69,
    },
    {
      id: 'ast-dario-avenue-schz',
      ticker: 'SCHZ',
      name: 'Schwab US Aggregate Bond ETF',
      assetClass: 'Renda Fixa',
      quantity: 32.40133,
      currentPrice: 117.9953,
      averagePrice: 120.2087,
      totalValue: 3824.07,
      unrealizedGainBRL: -70.88,
      unrealizedGainPercent: -1.82,
      allocationPercent: 0.53,
    },
    {
      id: 'ast-dario-avenue-copx',
      ticker: 'COPX',
      name: 'Global X Copper Miners ETF',
      assetClass: 'Internacional',
      quantity: 5.32523,
      currentPrice: 442.68,
      averagePrice: 494.8003,
      totalValue: 2357.22,
      unrealizedGainBRL: -277.68,
      unrealizedGainPercent: -10.54,
      allocationPercent: 0.32,
    },
    {
      id: 'ast-dario-avenue-vpl',
      ticker: 'VPL',
      name: 'Vanguard FTSE Pacific ETF',
      assetClass: 'Internacional',
      quantity: 2.74239,
      currentPrice: 604.1528,
      averagePrice: 610.3714,
      totalValue: 1656.84,
      unrealizedGainBRL: -17.07,
      unrealizedGainPercent: -1.02,
      allocationPercent: 0.23,
    },
    {
      id: 'ast-dario-avenue-vwo',
      ticker: 'VWO',
      name: 'Vanguard FTSE Emerging Markets ETF',
      assetClass: 'Internacional',
      quantity: 5.04663,
      currentPrice: 311.7205,
      averagePrice: 313.3015,
      totalValue: 1573.15,
      unrealizedGainBRL: -7.96,
      unrealizedGainPercent: -0.50,
      allocationPercent: 0.22,
    },
    {
      id: 'ast-dario-avenue-ibit',
      ticker: 'IBIT',
      name: 'iShares Bitcoin Trust Beneficial Interest',
      assetClass: 'Multimercado',
      quantity: 3.28792,
      currentPrice: 227.4532,
      averagePrice: 258.9151,
      totalValue: 747.76,
      unrealizedGainBRL: -103.56,
      unrealizedGainPercent: -12.16,
      allocationPercent: 0.10,
    },
    {
      id: 'ast-dario-avenue-shv',
      ticker: 'SHV',
      name: 'iShares Short Treasury Bond ETF',
      assetClass: 'Renda Fixa',
      quantity: 12.79974,
      currentPrice: 580.5959,
      averagePrice: 580.0162,
      totalValue: 7431.12,
      unrealizedGainBRL: 7.06,
      unrealizedGainPercent: 0.10,
      allocationPercent: 1.02,
    },
    {
      id: 'ast-dario-avenue-igf',
      ticker: 'IGF',
      name: 'iShares Global Infrastructure ETF',
      assetClass: 'Internacional',
      quantity: 15.47084,
      currentPrice: 333.064,
      averagePrice: 340.6528,
      totalValue: 5152.37,
      unrealizedGainBRL: -117.84,
      unrealizedGainPercent: -2.24,
      allocationPercent: 0.71,
    },
    {
      id: 'ast-dario-avenue-schd',
      ticker: 'SCHD',
      name: 'Schwab US Dividend Equity ETF',
      assetClass: 'Internacional',
      quantity: 28.87027,
      currentPrice: 180.9718,
      averagePrice: 182.5528,
      totalValue: 5225.47,
      unrealizedGainBRL: -44.90,
      unrealizedGainPercent: -0.85,
      allocationPercent: 0.72,
    },
    {
      id: 'ast-dario-avenue-qqqm',
      ticker: 'QQQM',
      name: 'Invesco NASDAQ 100 ETF',
      assetClass: 'Internacional',
      quantity: 3.57243,
      currentPrice: 1530.4607,
      averagePrice: 1464.3222,
      totalValue: 5467.47,
      unrealizedGainBRL: 236.25,
      unrealizedGainPercent: 4.52,
      allocationPercent: 0.75,
    },
  ],
},
];

// In-memory store that can be modified when simulated rebalancing occurs
let storePortfolios: Portfolio[] = JSON.parse(JSON.stringify(initialPortfolios));
let storePolicies: Policy[] = JSON.parse(JSON.stringify(initialPolicies));

export function getPortfoliosRepo(): Portfolio[] {
  return storePortfolios;
}

export function getPortfolioByIdRepo(id: string): Portfolio | undefined {
  return storePortfolios.find((p) => p.id === id);
}

export function updatePortfolioRepo(updated: Portfolio): void {
  const index = storePortfolios.findIndex((p) => p.id === updated.id);
  if (index !== -1) {
    storePortfolios[index] = updated;
  }
}

export function resetPortfoliosRepo(): Portfolio[] {
  storePortfolios = JSON.parse(JSON.stringify(initialPortfolios));
  return storePortfolios;
}

/**
 * Simula volatilidade súbita ou choque de mercado em uma carteira para gerar
 * um novo alerta crítico de desenquadramento em tempo real.
 */
export function simulateMarketShockRepo(targetPortfolioId?: string): {
  success: boolean;
  portfolio: Portfolio;
  affectedAsset: string;
  previousPercent: number;
  newPercent: number;
} {
  // Prioriza port-004 (que começa normal/enquadrada) ou a carteira solicitada
  let target = storePortfolios.find((p) => p.id === (targetPortfolioId || 'port-004'));
  if (!target) {
    target = storePortfolios[0];
  }

  // Encontra ativo de renda variável ou internacional para choque de alta
  const equityAssets = target.assets.filter((a) => a.assetClass === 'Renda Variável');
  const targetAsset = equityAssets.length > 0 ? equityAssets[0] : target.assets[0];

  const previousAllocation = targetAsset.allocationPercent;

  // Aplica choque expressivo de preço (+80%) no ativo para violar o teto do mandato com folga
  targetAsset.currentPrice = Math.round(targetAsset.currentPrice * 1.8 * 100) / 100;
  targetAsset.totalValue = targetAsset.quantity * targetAsset.currentPrice;

  // Recalcula valor total e percentuais da carteira
  const newTotalAum = target.assets.reduce((sum, a) => sum + a.totalValue, 0);
  target.totalAum = newTotalAum;
  for (const a of target.assets) {
    a.allocationPercent = Math.round((a.totalValue / newTotalAum) * 10000) / 100;
  }

  target.status = 'CRITICAL';
  const newAllocation = targetAsset.allocationPercent;

  return {
    success: true,
    portfolio: target,
    affectedAsset: targetAsset.ticker,
    previousPercent: previousAllocation,
    newPercent: newAllocation,
  };
}

export function getPoliciesRepo(): Policy[] {
  return storePolicies;
}

export function getPolicyByIdRepo(id: string): Policy | undefined {
  return storePolicies.find((p) => p.id === id);
}

export const defaultAssetClassThresholds: AssetClassThresholdConfig[] = [
  {
    assetClass: 'Renda Variável',
    minPercent: 10,
    targetPercent: 25,
    maxPercent: 35,
    warningTolerancePP: 2.0,
    criticalTolerancePP: 5.0,
    warningTriggerPercent: 33.0,
    criticalTriggerPercent: 40.0,
    sourceDescription: 'Mandato Bilateral IPS & CVM 175',
    notes: 'Ações B3, ETFs locais, BDRs Nível I/II',
  },
  {
    assetClass: 'Renda Fixa',
    minPercent: 40,
    targetPercent: 50,
    maxPercent: 65,
    warningTolerancePP: 3.0,
    criticalTolerancePP: 5.0,
    warningTriggerPercent: 62.0,
    criticalTriggerPercent: 70.0,
    sourceDescription: 'Resolução CMN 4.963 / ANBIMA',
    notes: 'Títulos públicos federais, Debêntures incentivadas, CDBs',
  },
  {
    assetClass: 'Internacional',
    minPercent: 0,
    targetPercent: 15,
    maxPercent: 20,
    warningTolerancePP: 2.0,
    criticalTolerancePP: 5.0,
    warningTriggerPercent: 18.0,
    criticalTriggerPercent: 25.0,
    sourceDescription: 'Resolução CVM 175 Anexo I (Teto Geral 20%)',
    notes: 'ETFs globais, fundos offshore 332, ADRs',
  },
  {
    assetClass: 'Multimercado',
    minPercent: 0,
    targetPercent: 10,
    maxPercent: 15,
    warningTolerancePP: 2.0,
    criticalTolerancePP: 3.0,
    warningTriggerPercent: 13.0,
    criticalTriggerPercent: 18.0,
    sourceDescription: 'Diretriz Interna de Risco & Alocação',
    notes: 'Fundos Macro, Quantitativos, Long & Short',
  },
  {
    assetClass: 'Caixa',
    minPercent: 2,
    targetPercent: 5,
    maxPercent: 10,
    warningTolerancePP: 1.0,
    criticalTolerancePP: 2.0,
    warningTriggerPercent: 9.0,
    criticalTriggerPercent: 12.0,
    sourceDescription: 'Gestão de Liquidez & Disponibilidades',
    notes: 'Operações compromissadas overnight, CDI diário',
  },
];

let storeAssetClassThresholds: AssetClassThresholdConfig[] = JSON.parse(
  JSON.stringify(defaultAssetClassThresholds)
);

export function getLimitsConfigRepo(portfolioId?: string): AssetClassThresholdConfig[] {
  if (portfolioId && portfolioId !== 'all') {
    const portfolio = storePortfolios.find((p) => p.id === portfolioId);
    if (portfolio && portfolio.mandateLimits.length > 0) {
      return portfolio.mandateLimits.map((ml) => {
        const base = storeAssetClassThresholds.find((t) => t.assetClass === ml.assetClass);
        return {
          assetClass: ml.assetClass,
          minPercent: ml.minPercent,
          targetPercent: ml.targetPercent,
          maxPercent: ml.maxPercent,
          warningTolerancePP: ml.warningTolerancePP ?? base?.warningTolerancePP ?? 2.0,
          criticalTolerancePP: ml.criticalTolerancePP ?? ml.tolerancePP ?? base?.criticalTolerancePP ?? 5.0,
          warningTriggerPercent:
            ml.warningTriggerPercent ?? (base?.warningTriggerPercent ?? ml.maxPercent - 2.0),
          criticalTriggerPercent:
            ml.criticalTriggerPercent ?? (base?.criticalTriggerPercent ?? ml.maxPercent + (ml.tolerancePP ?? 5.0)),
          sourceDescription: base?.sourceDescription,
          notes: base?.notes,
        };
      });
    }
  }
  return storeAssetClassThresholds;
}

export function updateLimitsConfigRepo(
  configs: AssetClassThresholdConfig[],
  portfolioId?: string
): Portfolio[] {
  // Atualiza thresholds armazenados globalmente
  storeAssetClassThresholds = JSON.parse(JSON.stringify(configs));

  // Aplica aos portfólios correspondentes
  for (const port of storePortfolios) {
    if (!portfolioId || portfolioId === 'all' || port.id === portfolioId) {
      for (const cfg of configs) {
        const existingLimit = port.mandateLimits.find((l) => l.assetClass === cfg.assetClass);
        if (existingLimit) {
          existingLimit.minPercent = cfg.minPercent;
          existingLimit.targetPercent = cfg.targetPercent;
          existingLimit.maxPercent = cfg.maxPercent;
          existingLimit.warningTolerancePP = cfg.warningTolerancePP;
          existingLimit.criticalTolerancePP = cfg.criticalTolerancePP;
          existingLimit.tolerancePP = cfg.criticalTolerancePP;
          existingLimit.warningTriggerPercent = cfg.warningTriggerPercent;
          existingLimit.criticalTriggerPercent = cfg.criticalTriggerPercent;
        } else {
          port.mandateLimits.push({
            assetClass: cfg.assetClass,
            minPercent: cfg.minPercent,
            targetPercent: cfg.targetPercent,
            maxPercent: cfg.maxPercent,
            tolerancePP: cfg.criticalTolerancePP,
            warningTolerancePP: cfg.warningTolerancePP,
            criticalTolerancePP: cfg.criticalTolerancePP,
            warningTriggerPercent: cfg.warningTriggerPercent,
            criticalTriggerPercent: cfg.criticalTriggerPercent,
            ruleSource: 'POLITICA_INTERNA',
          });
        }
      }
    }
  }

  return storePortfolios;
}

export function resetLimitsConfigRepo(): AssetClassThresholdConfig[] {
  storeAssetClassThresholds = JSON.parse(JSON.stringify(defaultAssetClassThresholds));
  return storeAssetClassThresholds;
}
