const fs = require('fs');

const wilsonObj = `{
  id: 'port-wilson-001',
  name: 'Carteira Wilson',
  clientName: 'Wilson',
  code: 'WILSON-001',
  manager: '',
  profile: 'Arrojado',
  benchmark: 'CDI',
  totalAum: 2078568.86,
  cashBalance: 0,
  lastRebalanced: '',
  status: 'NORMAL',
  assignedPolicyId: undefined,
  mandateLimits: [],
  assets: [
    {
      id: 'ast-wilson-itau-deb-incent-posfix',
      ticker: 'ITAU-DEB-INCENT-POSFIX',
      name: "Itaú Debêntures Incentivadas Pós-Fixado Renda Fixa",
      assetClass: 'Renda Fixa',
      sector: 'Fundo — Pós-fixado (CDI)',
      totalValue: 186141.70,
      allocationPercent: 8.96,
    },
    {
      id: 'ast-wilson-itau-index-us-tech-acoes',
      ticker: 'ITAU-INDEX-US-TECH-ACOES',
      name: "Itaú Index US Tech Ações",
      assetClass: 'Internacional',
      sector: 'Fundo — Índice EUA (Tech)',
      totalValue: 95850.90,
      allocationPercent: 4.61,
    },
    {
      id: 'ast-wilson-itau-janeiro-multimercado',
      ticker: 'ITAU-JANEIRO-MULTIMERCADO',
      name: "Itaú Janeiro Multimercado",
      assetClass: 'Multimercado',
      sector: 'Fundo — Multimercado',
      totalValue: 75635.44,
      allocationPercent: 3.64,
    },
    {
      id: 'ast-wilson-absolute-hidra-cdi',
      ticker: 'ABSOLUTE-HIDRA-CDI-INFRA-RF-CP',
      name: "Absolute Hidra CDI Seleção Infra Renda Fixa CP",
      assetClass: 'Renda Fixa',
      sector: 'Fundo — Crédito Privado',
      totalValue: 65715.25,
      allocationPercent: 3.16,
    },
    {
      id: 'ast-wilson-itau-sinfonia-mm-cp',
      ticker: 'ITAU-SINFONIA-MM-CREDITO-PRIVADO',
      name: "Itaú Sinfonia Multimercado Crédito Privado",
      assetClass: 'Multimercado',
      sector: 'Fundo — Crédito Privado',
      totalValue: 25410.96,
      allocationPercent: 1.22,
    },
    {
      id: 'ast-wilson-diferenciado-cp-rf',
      ticker: 'DIFERENCIADO-CREDITO-PRIVADO-RF',
      name: "Diferenciado Crédito Privado Renda Fixa",
      assetClass: 'Renda Fixa',
      sector: 'Fundo — Crédito Privado',
      totalValue: 70.62,
      allocationPercent: 0.00,
    },
    {
      id: 'ast-wilson-flexprev-sinfonia-vgbl',
      ticker: 'FLEXPREV-SINFONIA-MMCP-VGBL',
      name: "Flexprev Sinfonia Mm Cp Vgbl",
      assetClass: 'Multimercado',
      sector: 'Previdência — Multimercado Crédito Privado',
      totalValue: 173301.93,
      allocationPercent: 8.34,
    },
    {
      id: 'ast-wilson-itau-advanced-pvt-prev',
      ticker: 'ITAU-ADVANCED-PVT-MARKETS-PREV-VGBL',
      name: "Itau Advanced Pvt Markets Prev Mmcp Vgbl",
      assetClass: 'Multimercado',
      sector: 'Previdência — Multimercado Crédito Privado',
      totalValue: 164635.11,
      allocationPercent: 7.92,
    },
    {
      id: 'ast-wilson-deb-origemenergia-pre',
      ticker: 'DEB-ORIGEM-ENERGIA-PRE-1235',
      name: "DEB Origem Energia PRE 14,7% 15/12/2035",
      assetClass: 'Renda Fixa',
      sector: 'Prefixado',
      totalValue: 93924.00,
      allocationPercent: 4.52,
    },
    {
      id: 'ast-wilson-cpr-klabin',
      ticker: 'CPR-KLABIN-IPCA-656-0835',
      name: "CPR Klabin S.A. IPCA 6,56% 15/08/2035",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 77680.18,
      allocationPercent: 3.74,
    },
    {
      id: 'ast-wilson-deb-ecorodovias',
      ticker: 'DEB-ECORODOVIAS-IPCA-702-0639',
      name: "DEB Ecorodovias IPCA 7,02% 15/06/2039",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 64687.30,
      allocationPercent: 3.11,
    },
    {
      id: 'ast-wilson-cri-jhsf',
      ticker: 'CRI-JHSF-IPCA-755-1034',
      name: "CRI JHSF IPCA 7,55% 16/10/2034",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 64476.17,
      allocationPercent: 3.10,
    },
    {
      id: 'ast-wilson-deb-vale-619',
      ticker: 'DEB-VALE-IPCA-619-0535',
      name: "DEB Vale IPCA 6,19% 15/05/2035",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 58311.17,
      allocationPercent: 2.81,
    },
    {
      id: 'ast-wilson-deb-petrobras',
      ticker: 'DEB-PETROBRAS-IPCA-59-0640',
      name: "DEB Petrobras IPCA 5,9% 15/06/2040",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 57561.27,
      allocationPercent: 2.77,
    },
    {
      id: 'ast-wilson-deb-enauta',
      ticker: 'DEB-ENAUTA-IPCA-719-0630',
      name: "DEB Enauta IPCA 7,19% 15/06/2030",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 50792.71,
      allocationPercent: 2.44,
    },
    {
      id: 'ast-wilson-deb-brava',
      ticker: 'DEB-BRAVA-ENERGIA-IPCA-693-1033',
      name: "DEB Brava Energia IPCA 6,93% 15/10/2033",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 50138.34,
      allocationPercent: 2.41,
    },
    {
      id: 'ast-wilson-deb-isacteep',
      ticker: 'DEB-ISACTEEP-IPCA-631-0635',
      name: "DEB ISA CTEEP IPCA 6,31% 15/06/2035",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 49377.26,
      allocationPercent: 2.38,
    },
    {
      id: 'ast-wilson-cri-bild',
      ticker: 'CRI-BILD-PRE-1472-1130',
      name: "CRI Bild PRE 14,72% 18/11/2030",
      assetClass: 'Renda Fixa',
      sector: 'Prefixado',
      totalValue: 48565.77,
      allocationPercent: 2.34,
    },
    {
      id: 'ast-wilson-cra-zilor-1423',
      ticker: 'CRA-ZILOR-PRE-1423-1132',
      name: "CRA Zilor PRE 14,23% 15/11/2032",
      assetClass: 'Renda Fixa',
      sector: 'Prefixado',
      totalValue: 48046.11,
      allocationPercent: 2.31,
    },
    {
      id: 'ast-wilson-deb-celpe',
      ticker: 'DEB-CELPE-IPCA-631-0835',
      name: "DEB Celpe IPCA 6,31% 15/08/2035",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 47271.82,
      allocationPercent: 2.27,
    },
    {
      id: 'ast-wilson-deb-igua',
      ticker: 'DEB-IGUA-RJ-IPCA-833-0734',
      name: "DEB Igua RJ IPCA 8,33% 15/07/2034",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 44829.44,
      allocationPercent: 2.16,
    },
    {
      id: 'ast-wilson-deb-equatorial',
      ticker: 'DEB-EQUATORIAL-MARANHAO-IPCA-613-1231',
      name: "DEB Equatorial Maranhão IPCA 6,13% 15/12/2031",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 38276.20,
      allocationPercent: 1.84,
    },
    {
      id: 'ast-wilson-deb-taesa',
      ticker: 'DEB-TAESA-IPCA-616-1240',
      name: "DEB Taesa IPCA 6,16% 15/12/2040",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 37505.29,
      allocationPercent: 1.80,
    },
    {
      id: 'ast-wilson-deb-energisa',
      ticker: 'DEB-ENERGISA-MG-IPCA-624-1035',
      name: "DEB Energisa MG IPCA 6,24% 15/10/2035",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 32668.97,
      allocationPercent: 1.57,
    },
    {
      id: 'ast-wilson-cri-salta',
      ticker: 'CRI-SALTA-IPCA-77-0331',
      name: "CRI Salta IPCA 7,7% 17/03/2031",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 30509.47,
      allocationPercent: 1.47,
    },
    {
      id: 'ast-wilson-cra-zilor-1441',
      ticker: 'CRA-ZILOR-PRE-1441-1132',
      name: "CRA Zilor PRE 14,41% 15/11/2032",
      assetClass: 'Renda Fixa',
      sector: 'Prefixado',
      totalValue: 28435.45,
      allocationPercent: 1.37,
    },
    {
      id: 'ast-wilson-cri-solfacil',
      ticker: 'CRI-SOLFACIL-PRE-124-0131',
      name: "CRI Sólfácil PRE 12,4% 15/01/2031",
      assetClass: 'Renda Fixa',
      sector: 'Prefixado',
      totalValue: 25836.38,
      allocationPercent: 1.24,
    },
    {
      id: 'ast-wilson-deb-vale-62',
      ticker: 'DEB-VALE-IPCA-62-0535',
      name: "DEB Vale IPCA 6,2% 15/05/2035",
      assetClass: 'Renda Fixa',
      sector: 'Inflação (IPCA)',
      totalValue: 13782.64,
      allocationPercent: 0.66,
    },
    {
      id: 'ast-wilson-sp500-ganho-garantido',
      ticker: 'SP500-GANHO-GARANTIDO',
      name: "SP 500 Ganho Garantido",
      assetClass: 'Internacional',
      sector: 'Estruturado (COE)',
      totalValue: 129934.74,
      allocationPercent: 6.25,
    },
    {
      id: 'ast-wilson-cdb-di-unico',
      ticker: 'CDB-DI-UNICO',
      name: "CDB-DI",
      assetClass: 'Renda Fixa',
      sector: 'Pós-fixado (CDI)',
      totalValue: 23382.62,
      allocationPercent: 1.12,
    },
    {
      id: 'ast-wilson-avenue-sgov',
      ticker: 'SGOV',
      name: "iShares 0-3 Month Treasury Bond ETF",
      assetClass: 'Renda Fixa',
      sector: 'Avenue — offshore',
      quantity: 129,
      currentPrice: 530.90,
      averagePrice: 530.53,
      totalValue: 68691.22,
      allocationPercent: 3.30,
    },
    {
      id: 'ast-wilson-avenue-shv',
      ticker: 'SHV',
      name: "iShares Short Treasury Bond ETF",
      assetClass: 'Renda Fixa',
      sector: 'Avenue — offshore',
      quantity: 93,
      currentPrice: 581.64,
      averagePrice: 581.54,
      totalValue: 54262.61,
      allocationPercent: 2.61,
    },
    {
      id: 'ast-wilson-avenue-tflo',
      ticker: 'TFLO',
      name: "iShares Treasury Floating Rate Bond ETF",
      assetClass: 'Renda Fixa',
      sector: 'Avenue — offshore',
      quantity: 198,
      currentPrice: 267.12,
      averagePrice: 266.85,
      totalValue: 52859.82,
      allocationPercent: 2.54,
    },
  ],
}`;

let code = fs.readFileSync('src/server/portfolioRepo.ts', 'utf8');

code = code.replace(/    \],\n  \},\n\];/, '    ],\n  },\n' + wilsonObj + ',\n];');

fs.writeFileSync('src/server/portfolioRepo.ts', code);
