const fs = require('fs');

const darioObj = `  {
  id: 'port-dario-001',
  name: 'Carteira Dário',
  clientName: 'Dário Marques Neto',
  code: 'DARIO-001',
  manager: '',
  profile: 'Arrojado',
  benchmark: 'CDI',
  totalAum: 728022.72,
  cashBalance: 0,
  lastRebalanced: '',
  status: 'NORMAL',
  assignedPolicyId: undefined,
  mandateLimits: [],
  assets: [
    // ══════════════ ITAÚ — R$ 450.740,14 ══════════════
    // ── Fundos de Investimento — 15 fundos, R$ 235.994,68 ──
    {
      id: 'ast-dario-itubers-deb-cdi',
      ticker: 'ITUBERS-DEB-CDI',
      name: 'Itubers Debêntures Incentivadas CDI RF',
      assetClass: 'Renda Fixa',
      totalValue: 37173.23,
      allocationPercent: 5.11,
    },
    {
      id: 'ast-dario-itau-deb-posf',
      ticker: 'ITAU-DEB-POSF',
      name: 'Itaú Debêntures Incentivadas Pós-Fixado Renda Fixa',
      assetClass: 'Renda Fixa',
      totalValue: 30685.28,
      allocationPercent: 4.21,
    },
    {
      id: 'ast-dario-itau-itubers-di',
      ticker: 'ITAU-ITUBERS-DI',
      name: 'Itaú Itubers RF Referenciado DI',
      assetClass: 'Renda Fixa',
      totalValue: 27644.60,
      allocationPercent: 3.80,
    },
    {
      id: 'ast-dario-itau-deb-cdi-cp',
      ticker: 'ITAU-DEB-CDI-CP',
      name: 'Itaú Debêntures Incentivadas CDI RF CP',
      assetClass: 'Renda Fixa',
      totalValue: 27290.35,
      allocationPercent: 3.75,
    },
    {
      id: 'ast-dario-itau-legend-infra',
      ticker: 'ITAU-LEGEND-INFRA',
      name: 'Itaú Legend Infra Renda Fixa Crédito Privado',
      assetClass: 'Renda Fixa',
      totalValue: 22570.16,
      allocationPercent: 3.10,
    },
    {
      id: 'ast-dario-itau-artax-infra',
      ticker: 'ITAU-ARTAX-INFRA',
      name: 'Itaú Artax Infra Incentivado RF LP - RL',
      assetClass: 'Renda Fixa',
      totalValue: 21584.97,
      allocationPercent: 2.96,
    },
    {
      id: 'ast-dario-absolute-hidra',
      ticker: 'ABSOLUTE-HIDRA-CDI',
      name: 'Absolute Hidra CDI Seleção Infra Renda Fixa CP',
      assetClass: 'Renda Fixa',
      totalValue: 21522.76,
      allocationPercent: 2.96,
    },
    {
      id: 'ast-dario-itau-janeiro-infra',
      ticker: 'ITAU-JANEIRO-INFRA',
      name: 'Itaú Janeiro Infra Incentivado Renda Fixa',
      assetClass: 'Renda Fixa',
      totalValue: 12827.68,
      allocationPercent: 1.76,
    },
    {
      id: 'ast-dario-itau-janeiro-lp',
      ticker: 'ITAU-JANEIRO-LP',
      name: 'Itaú Janeiro Renda Fixa Longo Prazo',
      assetClass: 'Renda Fixa',
      totalValue: 11552.68,
      allocationPercent: 1.59,
    },
    {
      id: 'ast-dario-itau-global-dinamico-infra',
      ticker: 'ITAU-GLOBAL-DINAMICO-INFRA',
      name: 'Itaú Global Dinâmico Infra Renda Fixa Longo Prazo',
      assetClass: 'Renda Fixa',
      totalValue: 10779.25,
      allocationPercent: 1.48,
    },
    {
      id: 'ast-dario-itau-index-sp500',
      ticker: 'ITAU-INDEX-SP500',
      name: 'Itaú Index Ações Estratégia S&P 500',
      assetClass: 'Internacional',
      totalValue: 8134.64,
      allocationPercent: 1.12,
    },
    {
      id: 'ast-dario-itau-credito-bancario',
      ticker: 'ITAU-CREDITO-BANCARIO',
      name: 'Itaú Crédito Bancário Renda Fixa Crédito Privado',
      assetClass: 'Renda Fixa',
      totalValue: 2471.88,
      allocationPercent: 0.34,
    },
    {
      id: 'ast-dario-porto-paineira',
      ticker: 'PORTO-PAINEIRA-CDI',
      name: 'Porto Paineira CDI Seleção Infra Renda Fixa',
      assetClass: 'Renda Fixa',
      totalValue: 1116.06,
      allocationPercent: 0.15,
    },
    {
      id: 'ast-dario-itau-global-dinamico-lp',
      ticker: 'ITAU-GLOBAL-DINAMICO-LP',
      name: 'Itaú Global Dinâmico Renda Fixa Longo Prazo',
      assetClass: 'Renda Fixa',
      totalValue: 629.59,
      allocationPercent: 0.09,
    },
    {
      id: 'ast-dario-privilege-di',
      ticker: 'PRIVILEGE-DI',
      name: 'Privilege DI',
      assetClass: 'Renda Fixa',
      totalValue: 11.55,
      allocationPercent: 0.00,
    },

    // ── CDB, Renda Fixa e Estruturados — 1 posição, R$ 106.544,41 ──
    {
      id: 'ast-dario-cdb-di',
      ticker: 'CDB-DI',
      name: 'CDB-DI',
      assetClass: 'Renda Fixa',
      totalValue: 106544.41,
      allocationPercent: 14.63,
    },

    // ── Previdência — 3 posições, R$ 96.664,14 ──
    {
      id: 'ast-dario-pgbl-itubers-rf',
      ticker: 'PGBL-ITUBERS-RF',
      name: 'Pgbl Itubers Rf',
      assetClass: 'Renda Fixa',
      totalValue: 64574.65,
      allocationPercent: 8.87,
    },
    {
      id: 'ast-dario-absolute-delfos-prev',
      ticker: 'ABSOLUTE-DELFOS-PREV',
      name: 'Itau Absolute Delfos Prev Rf Cp Vgbl',
      assetClass: 'Renda Fixa',
      totalValue: 23887.81,
      allocationPercent: 3.28,
    },
    {
      id: 'ast-dario-pgbl-itubers-kinea',
      ticker: 'PGBL-ITUBERS-KINEA',
      name: 'Pgbl Itubers Kinea Prev Cp Rf',
      assetClass: 'Renda Fixa',
      totalValue: 8201.68,
      allocationPercent: 1.13,
    },

    // ── Ações (corretora) — 5 posições, R$ 11.536,91 ──
    {
      id: 'ast-dario-lfts11',
      ticker: 'LFTS11',
      name: 'INVESTO LFTS F11',
      assetClass: 'Renda Fixa',
      totalValue: 9109.17,
      allocationPercent: 1.25,
    },
    {
      id: 'ast-dario-nucl11',
      ticker: 'NUCL11',
      name: 'INVESTO NUCL CI',
      assetClass: 'Internacional',
      totalValue: 822.36,
      allocationPercent: 0.11,
    },
    {
      id: 'ast-dario-spcx34',
      ticker: 'SPCX34',
      name: 'SPACE X DRN',
      assetClass: 'Internacional',
      totalValue: 699.16,
      allocationPercent: 0.10,
    },
    {
      id: 'ast-dario-aapl34',
      ticker: 'AAPL34',
      name: 'APPLE DRN',
      assetClass: 'Internacional',
      totalValue: 677.92,
      allocationPercent: 0.09,
    },
    {
      id: 'ast-dario-nvdc34',
      ticker: 'NVDC34',
      name: 'NVIDIA CORP DRN ED',
      assetClass: 'Internacional',
      totalValue: 228.30,
      allocationPercent: 0.03,
    },

    // ══════════════ AVENUE — US$ 52.615,29 (R$ 277.282,58 @ 5,27) ══════════════

    // ── Renda fixa Avenue — total US$ 4.807,65 (R$ 25.336,31), 3 ativos ──
    {
      id: 'ast-dario-avenue-brazil-bond',
      ticker: 'BRAZIL-6.25-2036',
      name: 'Federative Republic of Brazil 6.25 22/05/36',
      assetClass: 'Internacional',
      sector: 'Avenue Tesouro — orig. US$ 1.935,05',
      totalValue: 10197.71,
      unrealizedGainBRL: -427.08,
      unrealizedGainPercent: -4.02,
      allocationPercent: 1.40,
    },
    {
      id: 'ast-dario-avenue-rededor-bond',
      ticker: 'RDEDOR-6.45-2035',
      name: "Rede D'Or Sao Luiz SA 6.45 09/09/35",
      assetClass: 'Internacional',
      sector: 'Avenue Bonds — orig. US$ 1.921,45',
      totalValue: 10126.04,
      unrealizedGainBRL: -631.50,
      unrealizedGainPercent: -5.87,
      allocationPercent: 1.39,
    },
    {
      id: 'ast-dario-avenue-suzano-bond',
      ticker: 'SUZANO-5.5-2036',
      name: 'Suzano SA 5.5 15/01/36',
      assetClass: 'Internacional',
      sector: 'Avenue Bonds — orig. US$ 951,15',
      totalValue: 5012.56,
      unrealizedGainBRL: -180.92,
      unrealizedGainPercent: -3.48,
      allocationPercent: 0.69,
    },

    // ── Fundos Avenue — 1 ativo, US$ 1.985,43 ──
    {
      id: 'ast-dario-avenue-pimco',
      ticker: 'PIMCO-GIS-EM-ST',
      name: 'PIMCO GIS EM S/T Lcl Ccy E USD Acc',
      assetClass: 'Internacional',
      sector: 'Avenue Fundos — orig. US$ 1.985,43',
      totalValue: 10463.22,
      unrealizedGainBRL: -76.78,
      unrealizedGainPercent: -0.73,
      allocationPercent: 1.44,
    },

    // ── ETFs Avenue — 24 ativos, US$ 45.822,21, 100% detalhados individualmente ──
    {
      id: 'ast-dario-avenue-vt',
      ticker: 'VT',
      name: 'Vanguard Total World Stock ETF',
      assetClass: 'Internacional',
      quantity: 45.72409,
      currentPrice: 831.6587,
      averagePrice: 842.4622,
      totalValue: 38028.06,
      unrealizedGainBRL: -492.80,
      unrealizedGainPercent: -1.28,
      allocationPercent: 5.22,
    },
    {
      id: 'ast-dario-avenue-tflo',
      ticker: 'TFLO',
      name: 'iShares Treasury Floating Rate Bond ETF',
      assetClass: 'Renda Fixa',
      quantity: 102.62911,
      currentPrice: 266.5566,
      averagePrice: 266.3985,
      totalValue: 27353.78,
      unrealizedGainBRL: 13.54,
      unrealizedGainPercent: 0.05,
      allocationPercent: 3.76,
    },
    {
      id: 'ast-dario-avenue-vti',
      ticker: 'VTI',
      name: 'Vanguard Total Stock Market ETF',
      assetClass: 'Internacional',
      quantity: 8.53218,
      currentPrice: 1963.3912,
      averagePrice: 1986.79,
      totalValue: 16751.80,
      unrealizedGainBRL: -199.89,
      unrealizedGainPercent: -1.18,
      allocationPercent: 2.30,
    },
    {
      id: 'ast-dario-avenue-shy',
      ticker: 'SHY',
      name: 'iShares 1-3 Year Treasury Bond ETF',
      assetClass: 'Renda Fixa',
      quantity: 37.42389,
      currentPrice: 428.6618,
      averagePrice: 431.613,
      totalValue: 16043.20,
      unrealizedGainBRL: -109.46,
      unrealizedGainPercent: -0.68,
      allocationPercent: 2.20,
    },
    {
      id: 'ast-dario-avenue-sgov',
      ticker: 'SGOV',
      name: 'iShares 0-3 Month Treasury Bond ETF',
      assetClass: 'Renda Fixa',
      quantity: 29.79420,
      currentPrice: 529.7931,
      averagePrice: 529.5296,
      totalValue: 15784.91,
      unrealizedGainBRL: 8.01,
      unrealizedGainPercent: 0.05,
      allocationPercent: 2.17,
    },
    {
      id: 'ast-dario-avenue-smh',
      ticker: 'SMH',
      name: 'VanEck Semiconductor ETF',
      assetClass: 'Internacional',
      quantity: 4.73197,
      currentPrice: 2850.8592,
      averagePrice: 2900.9242,
      totalValue: 13490.20,
      unrealizedGainBRL: -236.89,
      unrealizedGainPercent: -1.73,
      allocationPercent: 1.85,
    },
    {
      id: 'ast-dario-avenue-qual',
      ticker: 'QUAL',
      name: 'iShares MSCI USA Quality Factor ETF',
      assetClass: 'Internacional',
      quantity: 11.30096,
      currentPrice: 1150.8626,
      averagePrice: 1165.8294,
      totalValue: 13005.83,
      unrealizedGainBRL: -169.11,
      unrealizedGainPercent: -1.28,
      allocationPercent: 1.79,
    },
    {
      id: 'ast-dario-avenue-xle',
      ticker: 'XLE',
      name: 'The Energy Select Sector SPDR Fund',
      assetClass: 'Internacional',
      quantity: 35.47028,
      currentPrice: 346.4498,
      averagePrice: 341.7068,
      totalValue: 12288.69,
      unrealizedGainBRL: 168.22,
      unrealizedGainPercent: 1.39,
      allocationPercent: 1.69,
    },
    {
      id: 'ast-dario-avenue-aor',
      ticker: 'AOR',
      name: 'iShares Core Growth Allocation ETF',
      assetClass: 'Multimercado',
      quantity: 29.56509,
      currentPrice: 362.1544,
      averagePrice: 369.0054,
      totalValue: 10707.90,
      unrealizedGainBRL: -201.79,
      unrealizedGainPercent: -1.85,
      allocationPercent: 1.47,
    },
    {
      id: 'ast-dario-avenue-soxx',
      ticker: 'SOXX',
      name: 'iShares Semiconductor ETF',
      assetClass: 'Internacional',
      quantity: 3.99402,
      currentPrice: 2619.8751,
      averagePrice: 2692.2322,
      totalValue: 10463.85,
      unrealizedGainBRL: -289.01,
      unrealizedGainPercent: -2.69,
      allocationPercent: 1.44,
    },
    {
      id: 'ast-dario-avenue-iau',
      ticker: 'IAU',
      name: 'iShares Gold Trust',
      assetClass: 'Multimercado',
      quantity: 24.48049,
      currentPrice: 425.0255,
      averagePrice: 430.559,
      totalValue: 10404.82,
      unrealizedGainBRL: -135.44,
      unrealizedGainPercent: -1.29,
      allocationPercent: 1.43,
    },
    {
      id: 'ast-dario-avenue-vxus',
      ticker: 'VXUS',
      name: 'Vanguard Total International Stock ETF',
      assetClass: 'Internacional',
      quantity: 17.17076,
      currentPrice: 450.585,
      averagePrice: 460.3872,
      totalValue: 7736.41,
      unrealizedGainBRL: -168.75,
      unrealizedGainPercent: -2.13,
      allocationPercent: 1.06,
    },
    {
      id: 'ast-dario-avenue-qqq',
      ticker: 'QQQ',
      name: 'Invesco QQQ Trust Series 1',
      assetClass: 'Internacional',
      quantity: 1.56533,
      currentPrice: 3712.7677,
      averagePrice: 3387.7141,
      totalValue: 5811.70,
      unrealizedGainBRL: 508.82,
      unrealizedGainPercent: 9.60,
      allocationPercent: 0.80,
    },
    {
      id: 'ast-dario-avenue-vgt',
      ticker: 'VGT',
      name: 'Vanguard Information Technology ETF',
      assetClass: 'Internacional',
      quantity: 8.19890,
      currentPrice: 626.1287,
      averagePrice: 642.7819,
      totalValue: 5133.35,
      unrealizedGainBRL: -136.76,
      unrealizedGainPercent: -2.59,
      allocationPercent: 0.71,
    },
    {
      id: 'ast-dario-avenue-xlu',
      ticker: 'XLU',
      name: 'Utilities Select Sector SPDR ETF',
      assetClass: 'Internacional',
      quantity: 23.11727,
      currentPrice: 218.178,
      averagePrice: 227.9802,
      totalValue: 5043.07,
      unrealizedGainBRL: -227.19,
      unrealizedGainPercent: -4.31,
      allocationPercent: 0.69,
    },
    {
      id: 'ast-dario-avenue-schz',
      ticker: 'SCHZ',
      name: 'Schwab US Aggregate Bond ETF',
      assetClass: 'Renda Fixa',
      quantity: 32.40133,
      currentPrice: 117.9953,
      averagePrice: 120.2087,
      totalValue: 3824.07,
      unrealizedGainBRL: -70.88,
      unrealizedGainPercent: -1.82,
      allocationPercent: 0.53,
    },
    {
      id: 'ast-dario-avenue-copx',
      ticker: 'COPX',
      name: 'Global X Copper Miners ETF',
      assetClass: 'Internacional',
      quantity: 5.32523,
      currentPrice: 442.68,
      averagePrice: 494.8003,
      totalValue: 2357.22,
      unrealizedGainBRL: -277.68,
      unrealizedGainPercent: -10.54,
      allocationPercent: 0.32,
    },
    {
      id: 'ast-dario-avenue-vpl',
      ticker: 'VPL',
      name: 'Vanguard FTSE Pacific ETF',
      assetClass: 'Internacional',
      quantity: 2.74239,
      currentPrice: 604.1528,
      averagePrice: 610.3714,
      totalValue: 1656.84,
      unrealizedGainBRL: -17.07,
      unrealizedGainPercent: -1.02,
      allocationPercent: 0.23,
    },
    {
      id: 'ast-dario-avenue-vwo',
      ticker: 'VWO',
      name: 'Vanguard FTSE Emerging Markets ETF',
      assetClass: 'Internacional',
      quantity: 5.04663,
      currentPrice: 311.7205,
      averagePrice: 313.3015,
      totalValue: 1573.15,
      unrealizedGainBRL: -7.96,
      unrealizedGainPercent: -0.50,
      allocationPercent: 0.22,
    },
    {
      id: 'ast-dario-avenue-ibit',
      ticker: 'IBIT',
      name: 'iShares Bitcoin Trust Beneficial Interest',
      assetClass: 'Multimercado',
      quantity: 3.28792,
      currentPrice: 227.4532,
      averagePrice: 258.9151,
      totalValue: 747.76,
      unrealizedGainBRL: -103.56,
      unrealizedGainPercent: -12.16,
      allocationPercent: 0.10,
    },
    {
      id: 'ast-dario-avenue-shv',
      ticker: 'SHV',
      name: 'iShares Short Treasury Bond ETF',
      assetClass: 'Renda Fixa',
      quantity: 12.79974,
      currentPrice: 580.5959,
      averagePrice: 580.0162,
      totalValue: 7431.12,
      unrealizedGainBRL: 7.06,
      unrealizedGainPercent: 0.10,
      allocationPercent: 1.02,
    },
    {
      id: 'ast-dario-avenue-igf',
      ticker: 'IGF',
      name: 'iShares Global Infrastructure ETF',
      assetClass: 'Internacional',
      quantity: 15.47084,
      currentPrice: 333.064,
      averagePrice: 340.6528,
      totalValue: 5152.37,
      unrealizedGainBRL: -117.84,
      unrealizedGainPercent: -2.24,
      allocationPercent: 0.71,
    },
    {
      id: 'ast-dario-avenue-schd',
      ticker: 'SCHD',
      name: 'Schwab US Dividend Equity ETF',
      assetClass: 'Internacional',
      quantity: 28.87027,
      currentPrice: 180.9718,
      averagePrice: 182.5528,
      totalValue: 5225.47,
      unrealizedGainBRL: -44.90,
      unrealizedGainPercent: -0.85,
      allocationPercent: 0.72,
    },
    {
      id: 'ast-dario-avenue-qqqm',
      ticker: 'QQQM',
      name: 'Invesco NASDAQ 100 ETF',
      assetClass: 'Internacional',
      quantity: 3.57243,
      currentPrice: 1530.4607,
      averagePrice: 1464.3222,
      totalValue: 5467.47,
      unrealizedGainBRL: 236.25,
      unrealizedGainPercent: 4.52,
      allocationPercent: 0.75,
    },
  ],
}`;

let code = fs.readFileSync('src/server/portfolioRepo.ts', 'utf8');

// The file should have a closing bracket for `initialPortfolios` around line 434.
// Let's replace the last `];` right before `let storePortfolios` with `, ${darioObj} ];`
code = code.replace(/    \],\n  \},\n\];/, '    ],\n  },\n' + darioObj + ',\n];');

fs.writeFileSync('src/server/portfolioRepo.ts', code);
